
/**
 * Supabase Authentication for Documentation Site
 * Generated by @knowcode/doc-builder
 */

(function() {
    'use strict';
    
    // Skip auth check on login and logout pages
    const currentPage = window.location.pathname;
    if (currentPage === '/login.html' || currentPage === '/logout.html' || 
        currentPage.includes('login') || currentPage.includes('logout')) {
        return;
    }
    
    // Initialize Supabase client
    const { createClient } = supabase;
    const supabaseClient = createClient('https://xcihhnfcitjrwbynxmka.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjaWhobmZjaXRqcndieW54bWthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Mzc2MzcsImV4cCI6MjA2OTAxMzYzN30.zvWp3JFIR8fBIiwuFF5gqOR_Kxb42baZS5fsBz60XOY', {
        auth: {
            persistSession: true,
            autoRefreshToken: true,
            detectSessionInUrl: true
        }
    });
    
    // Check authentication and site access
    async function checkAuth() {
        try {
            // Get current user session
            const { data: { user }, error: userError } = await supabaseClient.auth.getUser();
            
            if (userError || !user) {
                redirectToLogin();
                return;
            }
            
            // Check if user has access to this site
            const { data: access, error: accessError } = await supabaseClient
                .from('docbuilder_access')
                .select('*')
                .eq('user_id', user.id)
                .eq('site_id', '4d8a53bf-dcdd-48c0-98e0-cd1451518735')
                .single();
            
            if (accessError || !access) {
                showAccessDenied();
                return;
            }
            
            // User is authenticated and has access
            console.log('User authenticated and authorized');
            document.body.classList.add('authenticated');
            
        } catch (error) {
            console.error('Auth check failed:', error);
            redirectToLogin();
        }
    }
    
    // Redirect to login page
    function redirectToLogin() {
        const currentUrl = window.location.pathname + window.location.search;
        const loginUrl = '/login.html' + (currentUrl !== '/' ? '?redirect=' + encodeURIComponent(currentUrl) : '');
        window.location.href = loginUrl;
    }
    
    // Show access denied message
    function showAccessDenied() {
        document.body.classList.add('authenticated'); // Show the body
        document.body.innerHTML = `
            <div style="display: flex; justify-content: center; align-items: center; height: 100vh; font-family: Inter, sans-serif;">
                <div style="text-align: center; max-width: 400px;">
                    <h1 style="color: #ef4444; margin-bottom: 1rem;">Access Denied</h1>
                    <p style="color: #6b7280; margin-bottom: 2rem;">You don't have permission to view this documentation site.</p>
                    <a href="/login.html" style="background: #3b82f6; color: white; padding: 0.75rem 1.5rem; border-radius: 0.5rem; text-decoration: none;">Try Different Account</a>
                </div>
            </div>
        `;
    }
    
    // Add logout functionality
    document.addEventListener('DOMContentLoaded', function() {
        const logoutLinks = document.querySelectorAll('a[href*="logout"]');
        logoutLinks.forEach(link => {
            link.addEventListener('click', async function(e) {
                e.preventDefault();
                await supabaseClient.auth.signOut();
                window.location.href = '/logout.html';
            });
        });
    });
    
    // Run auth check
    checkAuth();
    
})();
